version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DB_HOST: postgres
    volumes:
      - ./services/notifier:/app/notifier
    depends_on:
      - postgres

  cost-scanner:
    build: ./services/cost-scanner
    env_file: .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres

  recommendation-engine:
    build: ./services/recommendation-engine
    ports:
      - "8002:8002"
    env_file: .env
    environment:
      DB_HOST: postgres
    volumes:
      - ./services/notifier:/app/notifier
    depends_on:
      - postgres

  auto-scaler:
    build: ./services/auto-scaler
    env_file: .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres

  scheduler:
    build: ./services/scheduler
    env_file: .env
    environment:
      SCANNER_URL: http://cost-scanner:8001
      ENGINE_URL: http://recommendation-engine:8002
    depends_on:
      - cost-scanner
      - recommendation-engine

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api-gateway

  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./monitoring/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./monitoring/grafana/dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/dashboard-provider.yaml
      - ./monitoring/grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:
