global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'cost-optimizer-k8s'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - cost-optimizer
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: (api-gateway|cost-scanner)
